# Generated by Django 2.0 on 2020-09-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=3)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('min_units_for_discount', models.FloatField(default=0.0)),
                ('other_notes', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(blank=True, max_length=500)),
                ('primary_repr_name', models.CharField(max_length=100)),
                ('primary_email', models.CharField(max_length=100, unique=True)),
                ('primary_contact', models.CharField(max_length=20)),
                ('secondary_repr_name', models.CharField(max_length=100)),
                ('secondary_email', models.CharField(max_length=100)),
                ('secondary_contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Suppliers'),
        ),
    ]
