# Generated by Django 2.0 on 2020-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(default='ABC', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='other_notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
