# Generated by Django 2.0 on 2020-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20200927_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='auth_key',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
